version: '3.9'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auction_house
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'